### ISSUE TITLE
As a user I want to be able to look up precise definitions of terminology used by the platform (isolate, pool, etc.)

### ISSUE THREAD

**Issue by sgalkina** [DD-DeCaF/decaf-metabolica#6]
_From @phantomas1234 on March 1, 2017 10:6_

A more thorough explanation of the terminology in the File specification for
strains upload popup window would be helpful.

_Copied from original issue: DD-DeCaF/decaf-frontend#10_

**Comment by phantomas1234** [comment]
No longer relevant.
