### ISSUE TITLE
Add google analytics to platform

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/decaf-metabolica#8]

**Comment by Midnighter** [comment]
There was a concern raised during the DD-DeCaF project meeting that Google Analytics is commonly interrupted by AdBlockers and the like (I'm such a user myself). I see two alternatives:

1. Self-hosted analytics via [piwik](https://piwik.org/).
2. Spend time on getting our ELK stack to a working fashion, optimize the information recorded, and build the kind of Kibana dashboard for what we want to see.
